export default {
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  REORDER_TODO: 'REORDER_TODO',
  TOGGLE_SELECT_TODO: 'TOGGLE_SELECT_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  COMPLETE_SELECTED: 'COMPLETE_SELECTED',
  REMOVE_COMPLETED: 'REMOVE_COMPLETED',
};